services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kv6084242kv!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - recruiting_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: recruiting_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - recruiting_network

  api:
    build: .
    container_name: recruiting_api
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_PASSWORD=Kv6084242kv!
      - JWT_SECRET=your_super_secret_key_123
      - JWT_EXPIRES_IN=24h
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq
    networks:
      - recruiting_network

  nginx:
    image: nginx:latest
    container_name: recruiting_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./recruiting-frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - recruiting_network

volumes:
  mssql_data:
    driver: local

networks:
  recruiting_network:
    driver: bridge
